### ISSUE TITLE
[REQ] License and others

### ISSUE THREAD

**Issue by MarcoRavich** [catfact/depops#1]
Hi there, thanks again for this cool work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [AUDIO category](https://github.com/forart/HyMPS#-) \ [Tools section](https://github.com/forart/HyMPS/blob/main/A_Tools.md#--) \ [Restoring subsection](https://github.com/forart/HyMPS/blob/main/A_Tools.md#restoring-)), can you please specify the license for it ?

As you know, expliciting licensing terms is extremely important to let anyone better/faster understand how to reuse/adapt/modify sources (and not only) in other open projects and vice-versa.

The license file omission causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/catfact/depops/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/catfact/depops/?label=LICENSE)

You can easily set one using the GH's license wizard tool.

We also suggest you to keep in consideration to establish some kind of collaboration both with [Python Audio Restoration Suite](https://github.com/HENDRIX-ZT2/pyaudiorestoration#readme) by @HENDRIX-ZT2 and [DEVINYL](https://github.com/matiaszanolli/devinyl#readme) by @matiaszanolli, that are the most interesting projects on the scene.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by catfact** [comment]
https://github.com/catfact/depops/blob/main/LICENSE.md

**Comment by catfact** [comment]
its tempting to just take the thing down (this just represents an hour of quick work to share ideas with a collaborator a few years ago)

but i added the "unlicense" - it's now in public domain
